{
 "title": "Search BE - Full Index Update",
 "time": { "from": "now-40d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "cicd.solr.fullindex.*.*" }
  ]
 },
 "panels": [
  { "title": "Full Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Full Index",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.fullindex.start), 'success_full_index')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.fullindex.fail_*), 'fail_full_index')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.fullindex.fail*,cicd.solr.fullindex.*.dev.main.mcc.fullindex.success), 'Total_full_index')"
    }
   ]
  },
  {
   "title": "Full Index components Duration",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.common.extract.duration, 8, 'avg'), 'extract')"
    },
    {
     "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.metadata.duration, 9, 'avg'), 'metadata')"
    },
    {
     "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.duration, 10, 'avg'), 'wall_flower')"
    },
    {
     "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.orch.metrics.duration, 10, 'avg'), 'orchestration')"
    }
   ]
  },
  {
   "title": "Success /Fail Ratio",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.fullindex.fail*), 'fail')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.fullindex.success), 'success')"
    }
   ]
  },
  { "title": "Extract", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Full Index Extracts",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.common.extract.start), 'total_extracts')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.common.extract.success), 'success_extracts')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.common.extract.fail*), 'fail_extracts')"
    }
   ]
  },
  {
   "title": "Extract Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 12 },
   "targets": [
    {
     "target": "cicd.solr.fullindex.*.dev.main.common.extract.duration"
    }
   ]
  },
  {
   "title": "Extract Success/Fail Ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.common.extract.success), 'success')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.common.extract.fail*), 'fail')"
    }
   ]
  },
  { "title": "Meta Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Full Index metadata",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.metadata.start), 'total_metadata')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.metadata.success), 'success_metadata')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.metadata.fail*), 'fail_metadata')"
    }
   ]
  },
  {
   "title": "Meta Data Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 22 },
   "targets": [
    {
     "target": "cicd.solr.fullindex.*.dev.main.mcc.metadata.duration"
    }
   ]
  },
  {
   "title": "Extract Success/Fail Ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.mcc.metadata.success), 'success')"
    },
    {
     "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.mcc.metadata.fail*), 'fail')"
    }
   ]
  },
  {
   "title": "Wall flower",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Wallflower",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.start), 'total_Wall_Flower')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.fail*), 'fail_Wall_Flower')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.success), 'success_Wall_Flower')"
      }
     ]
    },
    {
     "title": "Wall flower stages Duration",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.wallflower.steps.catchup_fi.duration, 10, 'avg'), 'catchup_fi')"
      },
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.wallflower.steps.catchup_nrt.duration, 10, 'avg'), 'catchup_nrt')"
      },
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.wallflower.steps.optimize.duration, 10, 'avg'), 'optimize')"
      },
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.wallflower.steps.regression.duration, 10, 'avg'), 'regression')"
      }
     ]
    },
    {
     "title": "Wall Flower Success/Fail Ratio",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.success), 'success')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.fail*), 'fail')"
      }
     ]
    },
    {
     "title": "WallFlower Duration",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "target": "cicd.solr.fullindex.*.dev.main.mcc.wallflower.metrics.duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Orachestration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Orachestration",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.orch.metrics.start), 'total_extracts')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.orch.metrics.success), 'success_Orchestration')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.dev.main.mcc.orch.metrics.fail*), 'fail_Orchestration')"
      }
     ]
    },
    {
     "title": "Orchestration stages Duration",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.orch.steps.index_tar.duration, 10, 'average'), 'index_tar')"
      },
      {
       "target": "alias(groupByNode(cicd.solr.fullindex.*.dev.main.mcc.orch.steps.cloud_deploy.duration, 10, 'average'), 'cloud_deploy')"
      }
     ]
    },
    {
     "title": "Orchestration Success/Fail Ratio",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.mcc.orch.metrics.success), 'success')"
      },
      {
       "target": "alias(countSeries(cicd.solr.fullindex.*.$env.main.mcc.orch.metrics.*), 'fail')"
      }
     ]
    },
    {
     "title": "Orachestration Duration",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "target": "cicd.solr.fullindex.*.dev.main.mcc.orch.metrics.duration"
      }
     ]
    }
   ]
  }
 ]
}